// <auto-generated />
namespace SaudePublica.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alterandooscamposdelocalizacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alterandooscamposdelocalizacao));
        
        string IMigrationMetadata.Id
        {
            get { return "202101292304052_Alterando os campos de localizacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
